name: Deploy Frontend

on:
  push:
   branches:
    - deploy

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build and Push Docker Image
        run: |
          TAG=$(git rev-parse --short HEAD)
          docker buildx build --push \
            --cache-from=type=registry,ref=${{ secrets.DOCKER_USERNAME }}/logit_frontend:latest \
            --cache-to=type=inline \
            -t ${{ secrets.DOCKER_USERNAME }}/logit_frontend:latest \
            -t ${{ secrets.DOCKER_USERNAME }}/logit_frontend:$TAG \
            -f deploy/Dockerfile deploy

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i <(echo "${{ secrets.EC2_SSH_KEY }}") ubuntu@${{ secrets.EC2_HOST }} << 'EOF'
            sh run.sh
          EOF
